[2013-10-29 17:47:33.131000]
ERROR
	Unhandled Error
Traceback from remote host -- Traceback unavailable
exceptions.AttributeError: 'NoneType' object has no attribute 'get'

[2013-10-29 17:50:06.697000]
ERROR
	Unhandled Error
Traceback from remote host -- Traceback unavailable
exceptions.AttributeError: 'NoneType' object has no attribute 'get'

[2013-10-29 17:52:20.523000]
ERROR
	Unhandled Error
Traceback from remote host -- Traceback unavailable
exceptions.AttributeError: 'NoneType' object has no attribute 'get'

